stages:        
  - copy
  - service_restart

copy-job: 
    stage: copy
    tags:
        - tio-mon-extension
    script:
    - echo "Copying the code..."
    - cp -r * /var/www/pendencias-api/
    - echo "Copy complete."

restart-service-job:
    stage: service_restart
    tags:
    - tio-mon-extension
    script:
    - echo "Stopping backend server."
    - systemctl stop pendencias_backend.service
    - echo "Server Stopped"
    - echo "Starting Server"
    - systemctl start pendencias_backend.service
    - echo "Server started"
    - systemctl status pendencias_backend.service